# TMC5130 Raw SPI Test
esphome:
  name: tmc5130-test

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

logger:
  level: DEBUG
  hardware_uart: USB_SERIAL_JTAG

external_components:
  - source:
      type: local
      path: custom_components

spi:
  clk_pin: GPIO12
  miso_pin: GPIO13
  mosi_pin: GPIO11

tmc5130_raw:
  cs_pin: GPIO10
